# Generated by Django 4.2.5 on 2023-10-08 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_odds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_won', models.BooleanField(default=False)),
                ('is_settled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('home', models.CharField(max_length=50)),
                ('away', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('stage', models.CharField(choices=[('sche', 'scheduled'), ('li', 'live'), ('fin', 'finished'), ('post', 'postponed'), ('pen', 'after penalty'), ('pend', 'pending results'), ('canc', 'match cancelled')], default='sche', max_length=5)),
                ('home_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('draw_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('away_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('pend', 'pending'), ('home', 'home win'), ('draw', 'match drawn'), ('away', 'away win'), ('void', 'match void')], default='pend', max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='BetTicketSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('home', 'home win'), ('draw', 'match drawn'), ('away', 'away win')], default=None, max_length=4)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bet_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sselections', to='main.betticket')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
            ],
        ),
    ]
