# Generated by Django 4.2.5 on 2023-11-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_match_away_alter_match_home_alter_match_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('sche', 'scheduled'), ('li', 'live'), ('fin', 'finished'), ('post', 'postponed'), ('pen', 'after penalty'), ('pend', 'pending results'), ('canc', 'match cancelled')], default='sche', max_length=10),
        ),
    ]
