# Generated by Django 4.2.5 on 2023-10-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='referee',
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
