# Generated by Django 4.2.5 on 2023-11-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_match_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='uploads/dp/'),
        ),
    ]
