# Generated by Django 4.2.5 on 2023-12-02 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtherTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockHash', models.CharField(max_length=256)),
                ('from_addr', models.CharField(max_length=256)),
                ('to', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('redeemed', models.BooleanField(default=False)),
                ('timeStamp', models.CharField(max_length=256)),
                ('txreceipt_status', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='referee',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
