# Generated by Django 4.2.5 on 2023-10-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_total_deposit_profile_total_deposit_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
