# Generated by Django 4.2.5 on 2023-12-25 13:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_bonus_profile_bonus_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethertransaction',
            name='txreceipt_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='KE', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_id',
            field=models.CharField(max_length=6),
        ),
    ]
