# Generated by Django 4.2.5 on 2023-12-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_betticket_prize_betticket_money_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betticket',
            old_name='Money',
            new_name='prize',
        ),
        migrations.RenameField(
            model_name='betticket',
            old_name='Money_currency',
            new_name='prize_currency',
        ),
    ]
