# Generated by Django 4.2.5 on 2024-01-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_profile_referee_alter_transaction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worldcoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
            ],
        ),
    ]
